version: '3'

services:

  centos:
    image: fssai/centos:${CENTOS_VER}
    build: 
      context: ./centos
      dockerfile: ${TYPE}.Dockerfile
      args: 
        - CENTOS_VER=${CENTOS_VER}

  nginx:
    image: fssai/nginx:${NGINX_VER}
    build: 
      context: ./nginx
      dockerfile: ${TYPE}.Dockerfile
      args:
        - CENTOS_VER=${CENTOS_VER}
        - NGINX_VER=${NGINX_VER}
    depends_on: 
      - centos

  node:
    image: fssai/node:${NODE_VER}
    build: 
      context: ./node
      dockerfile: ${TYPE}.Dockerfile
      args:
        - CENTOS_VER=${CENTOS_VER} 
        - NODE_VER=${NODE_VER}
    depends_on: 
      - centos