version: "3.4"
services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      #target: devel
      args: 
        - "SVN_URL=${SVN_URL}"
        - "SVN_USER=${SVN_USER}"
        - "SVN_PASS=${SVN_PASS}"
    image: foscos-web #:devel
    ports:
      - "80:80"
