version: "3"
services: 

  web:
    image: fssai/nginx
    ports:
      - "80:80"
    volumes: 
      - ./web/dist:/usr/share/nginx/html:ro
      - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
