version: "2"
services:

# Base Images --------------------------------------------------------------- #
  svn:
    image: ${REGISTRY}/svn
    build: 
      context: ./svn
      dockerfile: ${OS}.Dockerfile
      args: 
        - OS_VER=${OS_VER}

  node:
    image: ${REGISTRY}/node:${NODE_VER}
    build: 
      context: ./node
      dockerfile: ${OS}.Dockerfile
      args:
        - OS_VER=${OS_VER} 
        - NODE_VER=${NODE_VER}
  node_tag:
    extends: node
    image: ${REGISTRY}/node 

  maven:
    image: ${REGISTRY}/maven:${MAVEN_VER}
    build:
      context: ./maven
      dockerfile: ${OS}.Dockerfile
      args:
        - JAVA_VER=${JAVA_VER}
        - MAVEN_VER=${MAVEN_VER}
        - MAVEN_SHA=${MAVEN_SHA}
  maven_tag:
    extends: maven
    image: ${REGISTRY}/maven


