version: '3'
services:

  centos:
    image: fssai/centos:${CENTOS_VER}
    build:
      context: ./centos
      dockerfile: ${TYPE}.Dockerfile
      args: 
        - CENTOS_VER=${CENTOS_VER}
    
  nginx:
    image: fssai/nginx:${NGINX_VER}
    build: 
      context: ./nginx
      dockerfile: ${TYPE}.Dockerfile
      args:
        - CENTOS_VER=${CENTOS_VER}
        - NGINX_VER=${NGINX_VER}
    depends_on: 
      - centos

  node:
    image: fssai/node:${NODE_VER}
    build: 
      context: ./node
      dockerfile: ${TYPE}.Dockerfile
      args:
        - CENTOS_VER=${CENTOS_VER} 
        - NODE_VER=${NODE_VER}
    depends_on: 
      - centos

  java:
    image: fssai/java:${JAVA_VER}
    build:
      context: ./java
      dockerfile: ${TYPE}.Dockerfile
      args:
        - CENTOS_VER=${CENTOS_VER}
        - JAVA_VER=${JAVA_VER}
        - JAVA_URL=${JAVA_URL}
    depends_on:
      - centos

  maven:
    image: fssai/maven:${MAVEN_VER}
    build:
      context: ./maven
      dockerfile: ${TYPE}.Dockerfile
      args:
        - JAVA_VER=${JAVA_VER}
        - MAVEN_VER=${JAVA_VER}
        - MAVEN_URL=${MAVEN_URL}
        - MAVEN_SHA=${MAVEN_SHA}
    depends_on:
      - centos
      - java